FROM node:18-alpine as builder

WORKDIR /app
COPY frontend/package*.json ./
RUN npm install --omit=dev

COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
