FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/

EXPOSE 5555

CMD ["celery", "--app=app.celery_app.celery_app", "flower", "--host=0.0.0.0", "--port=5555"]
